import type { Config } from "tailwindcss";

/*
  Script for generating safelist
  [
    ...["w-", "h-"]
      .map((type) => ["full", 250, 70].map((size) => type + size))
      .flat(Infinity),
    ...[...Array(5).keys()]
      .map((i) =>
        ["grid-cols-", "col-span-", "row-span-"].map((type) =>
          ["", "sm:", "md:", "lg:"].map((size) => size + type + (i + 1)),
        ),
      )
      .flat(Infinity),
  ]
*/

export default {
  darkMode: "class",
  content: ["./{src,static}/**/*.{html,js,ts,svelte,md,yml,yaml}"],
  plugins: [],
  safelist: [
    "w-full",
    "w-250",
    "w-70",
    "h-full",
    "h-250",
    "h-70",
    "grid-cols-1",
    "sm:grid-cols-1",
    "md:grid-cols-1",
    "lg:grid-cols-1",
    "col-span-1",
    "sm:col-span-1",
    "md:col-span-1",
    "lg:col-span-1",
    "row-span-1",
    "sm:row-span-1",
    "md:row-span-1",
    "lg:row-span-1",
    "grid-cols-2",
    "sm:grid-cols-2",
    "md:grid-cols-2",
    "lg:grid-cols-2",
    "col-span-2",
    "sm:col-span-2",
    "md:col-span-2",
    "lg:col-span-2",
    "row-span-2",
    "sm:row-span-2",
    "md:row-span-2",
    "lg:row-span-2",
    "grid-cols-3",
    "sm:grid-cols-3",
    "md:grid-cols-3",
    "lg:grid-cols-3",
    "col-span-3",
    "sm:col-span-3",
    "md:col-span-3",
    "lg:col-span-3",
    "row-span-3",
    "sm:row-span-3",
    "md:row-span-3",
    "lg:row-span-3",
    "grid-cols-4",
    "sm:grid-cols-4",
    "md:grid-cols-4",
    "lg:grid-cols-4",
    "col-span-4",
    "sm:col-span-4",
    "md:col-span-4",
    "lg:col-span-4",
    "row-span-4",
    "sm:row-span-4",
    "md:row-span-4",
    "lg:row-span-4",
    "grid-cols-5",
    "sm:grid-cols-5",
    "md:grid-cols-5",
    "lg:grid-cols-5",
    "col-span-5",
    "sm:col-span-5",
    "md:col-span-5",
    "lg:col-span-5",
    "row-span-5",
    "sm:row-span-5",
    "md:row-span-5",
    "lg:row-span-5",
  ],
} as Config;
